version: '3.3'
services:
  prometheus:
    image: prom/prometheus:v2.17.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./sample.rule
        target: /etc/prometheus/sample.rule
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
        - ./grafana/provisioning/:/etc/grafana/provisioning/
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - type: bind
        source: ./alertmgr.yml
        target: /etc/alertmanager/alertmanager.yml
  movie-catalog-service:
    image: gspear/movie-catalog-service:0.0.1-SNAPSHOT
    container_name: movie-catalog-service
    ports:
      - 8081:8080
  ratings-data-service:
    image: gspear/ratings-data-service:0.0.1-SNAPSHOT
    container_name: ratings-data-service
    ports:
      - 8082:8080
  movie-info-service:
    image: gspear/movie-info-service:0.0.1-SNAPSHOT
    container_name: movie-info-service
    ports:
      - 8083:8080

volumes:
  prometheus_data: {}
  grafana_data: {}




